config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "movies#index"

  resources :movies do
    resources :comments, only: [:edit, :update, :new, :create]
  end

  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :movies, dependent: :destroy
  has_many :comments, dependent: :destroy       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def create
    @comment = Comment.new(comment_params.merge(movie_id: params[:movie_id], user_id: current_user.id))
    if @comment.save
      redirect_to movie_path(params[:movie_id])
    else
      render :new
    end
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to movie_path(@comment.movie)
    else
      render :edit
    end

  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  def index
    @movies = Movie.all
  end

  def show
    @comments = Comment.where(movie_id: params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
  end

  def create
    # @movie = Movie.new(movie_params)
    @movie = Movie.new(movie_params.merge(user_id: current_user.id))
    if @movie.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    if @movie.update(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie.destroy
    redirect_to root_path
  end

  private
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:title, :description, :runtime, :released, :genre, :actors, :director, :imdb_rating)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :second_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/comments/edit.html.erb
<%= form_with model: @comment, url: movie_comment_path do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>

app/views/comments/new.html.erb
<%= form_with model: @comment, url: movie_comments_path do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit %>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <div class="buttons">
    <% if user_signed_in? %>
      <%= link_to 'New Movie', new_movie_path %>
      <%= link_to 'Edit Profile', edit_user_path(current_user) %>
      <%= button_to 'Exit', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Home', root_path, class: "home" %>
      <%= link_to 'Log in', new_user_session_path, class: "link login" %>
      <%= link_to 'Sign up', new_user_registration_path, class: "link" %>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FilmTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |f| %>
  <!-- <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> -->

  <div>
    <%= f.label :title, style: "display: block" %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description, style: "display: block" %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :runtime, style: "display: block" %>
    <%= f.number_field :runtime %>
  </div>

  <div>
    <%= f.label :released, style: "display: block" %>
    <%= f.date_field :released %>
  </div>

  <div>
    <%= f.label :genre, style: "display: block" %>
    <%= f.text_field :genre %>
  </div>

  <div>
    <%= f.label :actors, style: "display: block" %>
    <%= f.text_field :actors %>
  </div>

  <div>
    <%= f.label :director, style: "display: block" %>
    <%= f.text_field :director %>
  </div>

  <div>
    <%= f.label :imdb_rating, style: "display: block" %>
    <%= f.text_field :imdb_rating %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <p>
    <strong>Title:</strong>
    <%= movie.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= movie.description %>
  </p>

  <p>
    <strong>Runtime:</strong>
    <%= movie.runtime %>
  </p>

  <p>
    <strong>Released:</strong>
    <%= movie.released %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= movie.genre %>
  </p>

  <p>
    <strong>Actors:</strong>
    <%= movie.actors %>
  </p>

  <p>
    <strong>Director:</strong>
    <%= movie.director %>
  </p>

  <p>
    <strong>Imdb rating:</strong>
    <%= movie.imdb_rating %>
  </p>

  <p>
    <strong>User:</strong>
    <%= movie.user_id %>
  </p>

</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Movies</h1>

<div id="movies">
  <% @movies.each do |movie| %>
    <%= render movie %>
    <p>
      <%= link_to "Show this movie", movie %>
    </p>
  <% end %>
</div>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @movie %>

<div>
  <%= link_to "Back to movies", movies_path %>

  <% if current_user == @movie.user %>
    <%= link_to "Edit this movie", edit_movie_path(@movie) %> |
    <%= button_to "Destroy this movie", @movie, method: :delete %>
  <% end %>

  <%= link_to 'Add comment', new_movie_comment_path(@movie) if user_signed_in? %>
  <% @comments.each do |comment| %>
    <br>
    <%= comment.user.email %>
    <br>
    <%= comment.body %>
    <br>
    <%= link_to 'Edit comment', edit_movie_comment_path(@movie, comment) if current_user == comment.user %>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= form_with model: @user, url: user_path do |f| %>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :second_name %>
  </div>


  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "current-password" %>
  </div>

  <%= f.submit "Update"  %>
<% end %>